### ISSUE TITLE
Admin request

### ISSUE THREAD

**Issue by mark-wiemer** [vscode-autohotkey/.github#3]
In order to automatically add items to my project board, [AutoHotkey for VS Code](https://github.com/users/mark-wiemer/projects/1), I'll need to add the `ADD_TO_PROJECT_PAT` (personal access token) for the [project management workflow](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/blob/main/.github/workflows/project-management.yml) to run. Please allow me to update the settings of the main repo so I can add this value to the secrets section and get this set up for us :)

**Comment by cweijan** [comment]
Ok, I have authorized you admin privileges.
